version: '3.4'

services:
  node:
    image: 'doublesharp/massa-node:latest'
    restart: always
    ports:
      - '31234:31234'
      - '31235:31235'
    volumes:
      - node-config:/massa/massa-node/config/
      - node-block_store:/massa/massa-node/block_store/

  client:
    image: 'doublesharp/massa-client:latest'
    restart: on-failure
    depends_on: 
      - node
    volumes:
      - client-config:/massa/massa-client/config/

volumes: 
  node-config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/node/config'
  node-block_store:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/node/block_store'
  client-config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/client/config'
      