version: '3.4'

services:
  node:
    image: 'massa-node'
    build:
      context: .
      target: massa-node
    restart: always
    ports:
      - '31234:31234'
      - '31235:31235'
    volumes:
      - node-config:/massa/massa-node/config/
      - node-block_store:/massa/massa-node/block_store/

  client:
    image: 'massa-client'
    build:
      context: .
      target: massa-client
    restart: on-failure
    depends_on: 
      - node
    volumes:
      - client-config:/massa/massa-client/config/

volumes: 
  node-config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/node/config'
  node-block_store:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/node/block_store'
  client-config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/client/config'
      